{{- if .Values.lakefsConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakefs.fullname" . }}
  labels:
    {{- include "lakefs.labels" . | nindent 4 }}
type: Opaque
data:
  database_connection_string: {{ .Values.databaseConnectionString | b64enc }}
  auth_encrypt_secret_key: {{ .Values.authEncryptSecretKey | b64enc }}
{{- end}}